class PrefixedReminder:
    """This class acts as a base class for other types of reminders.
    Classes that subclass it should override the `self.text` property
    """
    def __init__(self, prefix="Hey, don't forget to "):
        self.prefix = prefix
        self.text = prefix + '<placeholder_text>'


class PoliteReminder(PrefixedReminder):
    # inherits the parent class 
    def __init__(self, text, date=None): #init method modified to accept date variable 
        super().__init__(prefix="Please remember to ") # initiate this class by calling super and we are passing polite prefix
        self.text = self.prefix + text # sets a text property with the value generated by combining prefix and text we want

    def __iter__(self):
        return iter([self.text]) #returns an iterator of a single element list